### ISSUE TITLE
Rosetta fine-tuning notebook outputs float-64 image

### ISSUE THREAD

**Issue by camisowers** [angelolab/toffy#166]
**Is your feature request related to a problem? Please describe.**
The [rosetta fine-tuning notebook](https://github.com/angelolab/toffy/blob/main/templates/rosetta_finetuning.ipynb) produces stitched float-64 images. 

**Describe the solution you'd like**
We should implement the same logic as the `load_utils`, where the data type of the image array  does not change throughout any of the adjustments made with rosetta.

**Comment by whitneyt1** [comment]
Hello! 

When I work through the 4a notebook, everything runs successfully with the example panel and commercial matrix as a first pass. However, when running the second command under 2. Rosetta-Remove Signal Contamination I receive this error

`/Users/whitneytamaki/miniconda3/envs/toffy_env/lib/python3.8/site-packages/ark/utils/load_utils.py:174: UserWarning: The supplied non-float dtype int16 was overwritten to float64, because the loaded images are floats
  warnings.warn(f"The supplied non-float dtype {dtype} was overwritten to {data_dtype}, "`

My .bin and .json files were copied directly from the MIBI computer to my hard drive, and notebook 4a is the first notebook I have used to process the images. When I try to open the outputted .tiff files, they are corrupt and do not open.

**Comment by camisowers** [comment]
Hi Whitney, can you please post a screenshot of the code cell you ran and the full error message it outputted? I am currently working on fixing a few other 4a and rosetta-finetuning issues and this will be useful to add. Thank you!

**Comment by whitneyt1** [comment]
<img width="1096" alt="Screen Shot 2022-08-16 at 1 48 45 PM" src="https://user-images.githubusercontent.com/46573884/184982527-2e1fed69-d9f2-4eee-9129-2cb77032979b.png">

**Comment by camisowers** [comment]
Thanks! That warning message should not prevent the images from stitching, only indicates a change in file size. Which which tiffs will not open?

**Comment by whitneyt1** [comment]
all of the tiffs in the "stiched_images" "stiched_with_Au" and "stiched_with_Noodle" folders are not opening!

**Comment by ngreenwald** [comment]
Did you try FIJI? I think photoshop has issues with 64bit tiffs

**Comment by whitneyt1** [comment]
@ngreenwald  Thank you! it opens in QuPath no problem. Just not in preview.
