### ISSUE TITLE
Speed up toffy testing

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#216]
**Is your feature request related to a problem? Please describe.**
There are a number of watcher tests slowing everything down. 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/13770365/185511772-192e8638-920f-4e72-bf58-84ed7bac9c95.png">

**Describe the solution you'd like**
Make them fast!

**Describe alternatives you've considered**
Give up on ever getting PRs merged in a timely manner

**Comment by ackagel** [comment]
Spoke with Cami about this; looks like the issue is with actually building the chained watcher callbacks.  It's been this slow ever since it replaced the old callback system (it shot callback building time from <1s to ~15s).  Didn't seem like an issue at the time, but obviously 10mins for callback tests is pretty ludicrous.  I'll take this one since it's my original booboo 🩹

**Comment by ackagel** [comment]
After some more digging, looks like a graphics call in qc visualization is the culprit here.  These definitely don't need to run for every watcher test, so I'll go ahead and mock those calls in the watcher tests.

<img width="883" alt="Screen Shot 2022-08-18 at 5 12 33 PM" src="https://user-images.githubusercontent.com/36260163/185516131-e117d69e-2a23-4ffa-89b9-90241e252105.png">
<img width="719" alt="Screen Shot 2022-08-18 at 5 11 33 PM" src="https://user-images.githubusercontent.com/36260163/185516141-5e79ef2b-7556-4fdb-91f2-45d974500989.png">

**Comment by ackagel** [comment]
After even more digging, the qc viz was part of the problem, but pretty much every callback contributes to the issue: 

<img width="1037" alt="Screen Shot 2022-08-18 at 7 17 20 PM" src="https://user-images.githubusercontent.com/36260163/185530427-734f2de2-c632-437a-8373-9554fdeecc97.png">


Currently, the watcher tests validate that the correct callbacks and the correct fovs are used, via checking the outputs (file writes and some log text).  

To speed up the tests, we can [mock](https://docs.python.org/3/library/unittest.mock.html) all of the callbacks, and assert that the mocked objects/callbacks were called with the expected arguments.  We can then move functionality testing (output validation) into the `watcher_callbacks_tests.py`, which currently only tests that callback building works, not callback running.

This should result in both faster and more organized testing, but would be a bit of an overhaul to the current test setup.  I don't think it would take long time-wise.  ~1 day implementation + <2 days for the review cycle.  Speeding up the testing could be pretty helpful in the pre-workshop crunch...

@ngreenwald I can do this tomorrow or wait until after the workshop, your call.

**Comment by ngreenwald** [comment]
Is it because each watcher test is putting through data through so many operations? What if we use smaller bin files, and hence smaller tifs. Would that speed things up? 

I guess I still don't understand what's actually causing the latency

**Comment by ackagel** [comment]
There are multiple things affecting the latency; image_stitching (~12s-14s) is the biggest culprit right now, but anything from graphics calls (like in visualize_qc_metrics, or visualize_mph_metrics) to basic fileio also adds latency, especially when done multiple times.

A short term fix would be to move just image_stitching functionality tests into watcher_callback_tests.py, and mock the stitching call (reduces time by ~12-14s).  Going ahead and doing that with the rest of the callbacks wouldn't add much dev time at all, encourages that pattern for new added callbacks, and clears up the remaining ~10-20s of unnecessarily repeated callback run time in fov_watcher_tests.py.

**Comment by ngreenwald** [comment]
What about changing from using the current panel, to a panel with only a couple masses?

**Comment by ackagel** [comment]
That might help; could be a good short term fix (i.e pre-workshop).  I'll test it out and see how using one channel impacts test time.

Long term, we should definitely restructure the tests as above, so we can always test the fov_watcher regardless of how intensive any callbacks are.

**Comment by ackagel** [comment]
Trimming the panel down to three channels cleared up the image stitching time.  I also ended up mocking anything which saved a png, since those were each adding ~6 seconds per call.  From there, increasing the speed of the transfer simulation started to make a difference, so right now, with those changes we're at ~5s per test (40s total), which should be good for now.

<img width="886" alt="Screen Shot 2022-08-19 at 12 33 40 PM" src="https://user-images.githubusercontent.com/36260163/185694059-3dccb74c-79da-4d64-a580-b8be9027cad2.png">

I'll submit a pr with these changes.
