### ISSUE TITLE
4b, Normalization script sometimes produces an error when smoothing outliers

### ISSUE THREAD

**Issue by dtebaykin** [angelolab/toffy#307]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
The error is new_value is NaN in normalize.py around line 487.  It happens when both previous_vals and subsequent_vals are empty (Not certain how this happens, could be a very sparse file with little signal). Our temporary solution is to assign an intensity value of 0 to the offending outlier.

**Expected behavior**
There needs to be a check for whether both previous and subsequent arrays are empty.

**To Reproduce**
Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message. 

The error happens on 
line 490: smoothed_vals[outlier] = new_val 
Because the array expects a value, it does not accept a NaN.

This is a temporary solution to the problem:
<img width="931" alt="Screen Shot 2023-01-10 at 10 30 57 AM" src="https://user-images.githubusercontent.com/8460227/211633881-db1ffdbf-43ed-4b19-8dd3-6bc365084493.png">

**Comment by alex-l-kong** [comment]
@dtebaykin this is a very specific error that happens when the following holds true:

1. `outlier_idx` contains the last index in the list
2. `len(vals)` <= `smooth_range`

Some examples would be the following:

```
smooth_outliers(vals=[5, 10], outlier_idx=[1], smooth_range=2)
smooth_outliers(vals=[0], outlier_idx=[0], smooth_range=2)
```

This would cause both `previous_vals` and `subsequent_vals` to get set to empty lists, and the final mean gets taken on an empty list as well, causing the `NaN` error.

@ngreenwald I think we should at least have a sanity check for these particular cases, however not sure how common or expected it is to encounter them.

**Comment by ngreenwald** [comment]
We should figure out what the original cause of this is. It's clear that once it gets propagated to this calculation it's resulting in NaNs, but why is this happening in the first place? Is it a channel with no counts in any of the FOVs? A channel with 0 counts in a specific FOV? Based on what the input data looks like, we can figure out the best way to sanitize it.

**Comment by alex-l-kong** [comment]
@ngreenwald @dtebaykin indeed this will happen when the values of `mph_vals` are set to zero. The reason is because all the indices get labeled as outliers. Meaning on iteration 1 of `smooth_outliers`, both `previous_vals` and `subsequent_vals` will be set to empty lists.

**Comment by alex-l-kong** [comment]
@dtebaykin I would check your `pulse_heights_combined.csv` file. If all the `pulse_height` values for one mass are 0, that would cause this error.

**Comment by alex-l-kong** [comment]
@ngreenwald Mako ran into this same issue, can we escalate this to high priority and I can add the fix @dtebaykin suggested here.

**Comment by ngreenwald** [comment]
Which fix are you thinking?

**Comment by alex-l-kong** [comment]
Setting the average of the outliers to zero if `np.mean` returns `np.nan` (in this case, it would happen when there are no outliers since all the pulse heights for one mass is zero).

**Comment by ngreenwald** [comment]
If there are no pulse heights, we shouldn't do any normalization, since there are no counts. There's already logic to manually set the normalization value when there are too few fovs, could we add something similar for this?

**Comment by alex-l-kong** [comment]
@ngreenwald coming back to this one, yes we could choose to use a lower `min_obs` parameter in `fit_mass_mph_curve` to bypass outlier checking. As it stands, however, `min_obs` cannot be changed from its default 10.

In `create_fitted_pulse_heights_file`, we can check if all the pulse heights are 0. If `True`, then intentionally set `min_obs` to an unreasonably high value so the outlier smoothing cannot run. Otherwise, we can leave `min_obs` as 10.
