### ISSUE TITLE
4b normalization produces images with negative expression values

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/toffy#308]
**Describe the bug**
Expression values on certain channels (48, 56, 69, 70) on certain FOVs on certain runs, were inverted after running normalization notebook. When the effected image were inverted again by multiplying by -1, the original image was restored (see example image attached).

Cohort size = 46 separate runs, ~650 individual FOVs
list of FOVs effected (image attached)

**Expected behavior**
No image should have negative expression values. 

**To Reproduce**
Can provide the link to dataset

<img width="1984" alt="Screenshot 2023-01-19 at 3 44 03 PM" src="https://user-images.githubusercontent.com/62519486/213778668-e07d6f0a-a5a0-4da5-89b8-c49c9b786b17.png">
<img width="411" alt="Screenshot 2023-01-20 at 12 37 11 PM" src="https://user-images.githubusercontent.com/62519486/213779596-fd2ffe03-9700-45c4-84f3-551a7ff4ccc1.png">

**Comment by alex-l-kong** [comment]
I'll leave this issue open for now, but it appears the discussion will be moving to #317.

**Comment by alex-l-kong** [comment]
Talked with Mike about this at MIBI meeting today, he's following up Hadeesha and Inna on making sure they're using the correct tuning curve. We had way too many tuning curves across the different machines and they really need to ensure they're using a standardized one that doesn't give negative values for certain mass values.

The issue seems most definitely an issue with how lab members are using the tuning curve, not the generation or calculation of the tuning curve/normalization coefficients itself.

**Comment by ngreenwald** [comment]
This will be closed by #325
