### ISSUE TITLE
Extracted images have weird artifact

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#389]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
A subset of the extracted images have a weird image artifact, which to me looks like the pixels are being offset from their true location. This is not present in the images on the ionpath tracker, so it's something about our extraction/saving that isn't working. 

<img width="471" alt="image" src="https://github.com/angelolab/toffy/assets/13770365/3b831b21-0ed0-4f5c-badd-37efce0ae390">

**Expected behavior**
Successful extraction, or an error message

**To Reproduce**
Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message.

**Comment by alex-l-kong** [comment]
Verified that for these corrupted images, the .bin file was not fully extracted. I want to first verify if this is a feature across all the CACs or whether it's Drago-specific.

If the former, then unfortunately, we can no longer assume that if a .bin and .json file get written, the .bin file. The current setup is fine, just that we'll need to implement a way to go back and check if a FOV was actually written or not. The tricky part is for the FOVs with "copy lag", there's approx. an hour delay from when the .json file gets written and when the .bin file actually completes. I'd hesitate to wait a whole hour for each FOV before extracting since the watcher could take a week or even longer if there are 150+ FOVs in the cohort (as with one of Bryan's runs).

I think it's fine to loop through each .bin at the end of the FOV callbacks and see if any of them have a timestamp greater than their corresponding .json file. If so, then re-extract the data.
