### ISSUE TITLE
Image line artifacts

### ISSUE THREAD

**Issue by srivarra** [angelolab/toffy#59]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

Closes #48.

Due to malfunctions caused by the instrument there are traces of horizontal steaks throughout each channel across an image. Each are one pixel in height and vary in length. These streaks are present in every channel with varying degrees of visibility.

**Design overview**

1. Detection Algorithm
This function is not intended to be user callable. For each input image we select the noodle channel and apply the detection algorithm on it. We can modify the image by increasing the contrast, or using other filters which increase the brightness of the streaks. For each streak on each modified noodle channel, we collect information required for detection and place it in a temporary data structure. We can check any new streak against this current data structure and only add them if it doesn't already exist.

2. Streak Correction
This function is not intended to be user callable. For each image, we have it's corresponding streak data. With this we can go over each channel and apply some form of a smoothing, de-noising, or averaging algorithm. We can delete the streak dateset after each image has been cleaned. Each image can be collected, and the whole batch can be returned back to the user.

**Design list/flowchart**

![Image Line Artifacts-Fix1](https://user-images.githubusercontent.com/8909315/158460173-24640f0c-8c99-43c0-8866-0da0226502f4.svg)

**Required inputs**

The input is a folder containing tiffs of each channel per image. The images are n by n pixels, with m channels.

**Output files**

The outputs are the same images and channels from the input, but with the streaks removed.

Return the detected streaks for investigative / development purposes. 

**Section 2: Implementation details**

User facing function for streak correction.

```python
def streak_correction(
    fov: Union[str, pathlib.Path],
    channel: str = "noodle",
    method: Optional[str] = "avg",
    streak_output: bool = False,
) -> Optional[np.ndarray]:
    """Takes a `fov` directory and uses a user specified channel for streak detection. Once all the streaks have been detected,
    they are `corrected` via a user given method. It defaults to "averaging". If `streak_output` is `True`, the function
    returns a binary mask where `1` signifies a pixel belonging to a streak. Saves the corrected `fov` into a new directory with
    `corrected` in the name.

    Args:
        fov (typing.Union[str, pathlib.Path]): A directory containing the fov and all it's channels for correction.
        channel (str): The channel used for identifying and removing the streaks. Defaults to "noodle".
        method (Optional[str], optional): The method for applying the correction once the streaks are found. Defaults to "avg".
        streak_output (bool): If `True`, returns a binary mask containing information for the detected streaks. Defaults to "False"

    Returns:
        Optional[np.ndarray]: A binary mask for the detected streaks.
    """
```

User hidden function for getting the streaks
```python

def _streak_detection(channel_np: np.ndarray) -> np.ndarray:
    """Detects streaks in the noodle channel by increasing contrast, and other methods if necessary.

    Args:
        channel_np (np.ndarray): The numpy array representation of the tifffile of the selected channel.

    Returns:
        np.ndarray: A binary mask for the detected streaks.
    """
```

User hidden function for applying the streak correction.
```python

def _streak_correction(
    channel_np: np.ndarray, streaks: np.ndarray, method: Optional[str] = "avg"
) -> np.ndarray:
    """Corrects streaks for a specific channel using a user defined method.

    Args:
        channel_np (np.ndarray): The numpy array representation of the tifffile of the selected channel.
        streaks (np.ndarray): A binary mask containing the locations of the streaks.
        method (Optional[str], optional): The method for applying the correction. Defaults to "avg".

    Returns:
        np.ndarray: Returns the corrected channel in the numpy format.
    """
```

Algorithms for Streak Detection:

1. [Probabilistic Hough Transform](https://scikit-image.org/docs/dev/auto_examples/edges/plot_line_hough_transform.html)
2. [Sobel Edge Detection](https://scikit-image.org/docs/stable/api/skimage.filters.html#skimage.filters.sobel_h)
3. [Laplace Operator](https://scikit-image.org/docs/stable/api/skimage.filters.html#skimage.filters.laplace)

Algorithms for Streak Correction:

1. Averaging in the *y* direction. (this would be the ideal one)
2. Anything else if *y* averaging doesn't work well. (update here)

**Control flow**

1. Users should have a `fov` directory. They then call ``` streak_correction``` with the directory, and a correction method if desired.
2.  Within ```streak_correction``` it loads the a user specified Tiff first and then calls ```_streak_detection``` (hidden to the user) and returns a binary mask where the streaks exist (if flagged True). 
3.  Next the function loops over each channel and calls ```_streak_correction``` with the binary mask, the method of correcting the streaks (defaults to averaging) along with the channel.
4. ```streak_correction``` returns the corrected file. All of these corrected channels get collected, and saved within a new directory, with `corrected` in the name. If  `streak_output`  is `True`, then it returns the binary mask.

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one. 

Total time estimate: 5 weeks.

1. Prototyping. *Weeks 1-3*
   1. Get the framework:
      1. Read and write tiff files
      2. Set up the control flow for `streak_correction`, `_streak_detection`, `_streak_correction`.
   2. Experiment with different different algorithms for streak detection.
2. Writing tests. *Weeks 1-3*
   1. Create fake, easy to work with data (not the fov-27-scan-1)
   2. Write tests with the prototype code as it's developed.
3. Performance adjustments. *Weeks 2-4*
   1. Profiling code to find bottlenecks.
   2. Async / Parallelization.
   3. GPU methods if available / easy to implement.
4. Implementing in toffy. *Weeks 3-5*
5. Code Review. *Weeks 1-5*

**Comment by srivarra** [comment]
@angelolab/computational_team

**Comment by ngreenwald** [comment]
Nice, first design doc! Couple comments:
1. Some channels are dimmer than other channels, which is why the streaks don't look exactly identical. However, if you increase the contrast, you can see that they're quite faint on some channels, much brighter on other channels, but they're all in the same spot. The goal I think should be to pick a channel where all of the streaks are present, identify all of them, and then apply a correction to each of the other channels. In the dataset I set you, the Noodle channel is a good one to find all of the streaks. 
2. For streak correction algorithms, the first one we should try is replacing the pixels in the streak with the average of the pixel directly above and directly below
3. As we're testing this out, we're going to want to verify that it's identifying the correct streaks. Having an optional flag to save a binary mask containing all of the streaks will be helpful for initial testing. 

Once you've incorporated those changes, the next step will be to move on to section two of the design doc and lay out some more specifics. What type of streak detection algorithm do you think you'll use? What will the docstring of the user-callable function look like? How will it expect the input data to be formatted (spoiler, it will be one folder per FOV, with that folder containing one tiff per channel, just like I sent you)

**Comment by srivarra** [comment]
@ngreenwald Before I get to the milestones, how does it look so far?

**Comment by ngreenwald** [comment]
Looks great. Couple small comments: 

- In general, we represent tifs as numpy arrays. The reason to have a tiffile format, instead of numpy array, is for the metadata. However, we don't store any metadata in our tifs, so it makes things a lot simpler to just pass around numpy arrays. 
- The channel used to detect the streaks should be a user-supplied parameter. I'm guessing noodle will work the best, but the user should pass the name of the channel
- For the timeline, the goal should be to over-estimate the amount of time it will take in your first few PRs. This is actually hard to do, so it'll be good to get in this habit.
