### ISSUE TITLE
Installing dependencies - ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by maharahim** [angelolab/toffy#76]
The environment doesn't seem to have all dependencies when trying to run "Compensate_image_data" notebook.
 Current issue: 
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
ImportError: numpy.core.multiarray failed to import

Running import numpy.core.multiarray has no issues, but does not resolve the problem.

**Comment by ngreenwald** [comment]
We recently updated our ReadMe to be more descriptive, can you try from scratch installing?

If it persists, can you give some more information? What operating system are you using, what line is causing the error message, etc

**Comment by ackagel** [comment]
@ngreenwald that's the issue that happens when the numpy that builds mibi_bin_tool's cython code is different than the numpy it installs later.  This was allegedly not supposed to happen again, but there is a perma-fix involving some pyproject.toml settings.  I'll update mibi-bin-tools and tag a patched version.  I'll post here when that's done

**Comment by ackagel** [comment]
This should be fixed now.  To get the updated codebase, run these commands within the toffy folder:
```
git pull
conda activate toffy_env
pip install -r requirements.txt
```

**Comment by maharahim** [comment]
Thanks! Finally got all the packages to install!
