### ISSUE TITLE
TMA remapping fails with multiple input FOVs of the same name

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/toffy#83]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
When the manual JSON file contains multiple FOVs with the same name, we would expect those to get flagged as duplicates and displayed in the counter. However, the notebook instead only displays the second instance of the duplicated name

**To Reproduce**
Create a JSON with identically named FOVs. 
Load into remapping noteobok

**Comment by alex-l-kong** [comment]
Instead of displaying this in the error box, I think it's easiest to have a separate function that validates all FOV names are unique in a given list of manual FOVs. We can run that function right after we load `manual_fovs` in and throw an error if this is found.

Handling it in the error message could cause confusion. If there are two `'R1C1'` in the `manual_fovs` list, and both those `'R1C1'` values got flagged for any one of the three errors we catch, it would be more cumbersome on the user's end to figure out which `'R1C1'` corresponds to which error.

**Comment by ngreenwald** [comment]
How about instead of an error, it adds _duplicate to the name of any FOVs that are duplicated? This way the user doesn't have to regenerate the JSON file, which could take a while.

**Comment by ngreenwald** [comment]
Then there would be R1C1, and R1C1_duplicate, in the list of FOV names, and the mapping could continue as it does right now
